version: '3'
services:
  geth:
    build: ./geth
    container_name: geth
    tty: true
    stdin_open: true
    ports:
      - "8546:8546"
  postgres:
    build: ./postgres
    container_name: postgres
    tty: true
    stdin_open: true
    environment:
      POSTGRES_PASSWORD: chainlink
      POSTGRES_USER: chainlink
      POSTGRES_DB: chainlink
    ports:
      - "5432:5432"